### PR TITLE
feat: astro language support

### PR DESCRIPTION
**Pull request by imkarthikk**
Adding Astro support.

Closed the previous PR #181 due to branch name change.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
Need any help with this @imkarthikk I'd love to have it included too :)

**Comment by alstr** [comment]
Closing due to inactivity but feel free to update.

**Comment by ChrisChinchilla** [comment]
@alstr I don't think there was any activity, but the OP was waiting for your feedback?

**Comment by alstr** [comment]
I think we're just missing tests. If they can be added then it's good to go.

**Pull request closed without merging**
