### PR TITLE
Add marker patterns for SCSS

### PR DESCRIPTION
**Pull request by jonrkarr**

### CODE REVIEW

**Comment by alstr** [comment]
Hey, thanks for the contribution.

The markers for Sass are already in `syntax.json`, so we have a duplicate here unless I'm missing something.

SCSS is a new one though; it would be great if you could write a quick test for it in the style of the existing languages.

Thanks!

**Review by alstr — CHANGES_REQUESTED** [review]
Just need to remove duplicate Sass entry and add test for SCSS.

**Comment by jonrkarr** [comment]
Removed redundant Sass definition. Added test for SCSS.

**Comment by alstr** [comment]
Thanks!

**Pull request merged**
