### PR TITLE
WIP: Add option for CUSTOM language definitions

### PR DESCRIPTION
**Pull request by drkameleon**
As per https://github.com/alstr/todo-to-issue-action/issues/104

P.S. I'm not sure if it's exactly what you suggested, plus - as I've already mentioned - I'm not a Python guy at all, so, it may have ended up looking like Swahili lol. If it doesn't, then I would love to hear your comments.

### CODE REVIEW

**Comment by alstr** [comment]
I've updated the Python a little and it seems to append the custom languages fine. I've not been able to test it with any actual custom files though yet. Don't know if you want to try it out? You'll just have to make a couple of changes so it doesn't run the prebuilt action image, described here: https://github.com/alstr/todo-to-issue-action/issues/101. Thanks!

**Review by drkameleon — COMMENTED** [review]
Looks great! (As I said, I'm not very familiar with Python, hence the weird way of writing things, and obviously not with the specifics of your codebase, but I believe it should work fine)

**Comment by drkameleon** [comment]
> I've updated the Python a little and it seems to append the custom languages fine. I've not been able to test it with any actual custom file yet though. Don't know if you want to try it out? You'll just have to make a couple of changes so it doesn't run the prebuilt action image, described here: #101. Thanks!

I'll try to test it myself and I will let you know how it goes! 😉 

Thanks!

**Comment by alstr** [comment]
No problem, thanks! We'll need to add the input to `action.yml` as well.

**Comment by alstr** [comment]
Closing due to inactivity but feel free to reopen.

**Pull request closed without merging**
