### PR TITLE
Add support for custom languages

### PR DESCRIPTION
**Pull request by Christoph-Koschel**
Finally, after the rough semester start, I found some time to work on this feature.

### CODE REVIEW

**Comment by Christoph-Koschel** [comment]
Note: In my last commit, I changed the test URL to the main repo. However, the testing file does not exist in the main repo because it will be "created" through my PR. Therefore, the test is failing.

**Comment by alstr** [comment]
Thanks very much for the contribution, I'll aim to take a look over this as soon as I can.

PS, if it helps, there was an attempt at this previously, and it was almost complete: https://github.com/alstr/todo-to-issue-action/pull/105

**Comment by Christoph-Koschel** [comment]
Hey, it's been a few months and I wanted to know if the PR is still under review

**Comment by alstr** [comment]
Thanks for your patience and sorry for the delay, I've just not had chance until now.

It all seems good. I've not tested it myself; does it run okay for you?

One small thing, would you be able to replace 'costume' with 'custom'? I'm assuming that's what you meant and it's not a big deal, just makes things easier in future! :smile:

Thanks.

**Comment by Christoph-Koschel** [comment]
I have fixed the typo. Also loading costume languages works like a charm. I also wrote some unit tests, so I think it should work smoothly.

**Comment by alstr** [comment]
I've merged it and created a new release so you should be good to try it out. I had to slightly change a URL in the tests but other than that the tests seem to be running fine. Thanks for the contribution!

**Pull request merged**
