### PR TITLE
add zig language support

### PR DESCRIPTION
**Pull request by hasanpasha**

### CODE REVIEW

**Comment by alstr** [comment]
Thanks for the contribution; would you be able to add some tests?

**Comment by hasanpasha** [comment]
Hey @alstr, sorry for the delayed response. I have added some tests, but they all failed for some reason, despite having everything in place. Can you please review them?

**Comment by alstr** [comment]
Because the `ace_mode` of Zig is `text` (see [here](https://github.com/github-linguist/linguist/blob/39fd5e93de98de3434cb3e857c5b1972c418f8c5/lib/linguist/languages.yml#L8271)), you should update the `text` tests rather than add new ones for `zig`.

**Comment by alstr** [comment]
Closing due to inactivity but feel free to update.

**Pull request closed without merging**
