### PR TITLE
Add support for ABAP and ABAP CDS languages

### LINKED ISSUE #85: Add support for ABAP language
Here's an example of how code with TODOs would look like:

```abap
REPORT zfoobar.

WRITE 'Hello World'.

* TODO This is a new single-line to-do
DATA moo TYPE i VALUE 2.
WRITE moo. " TODO This is an end-of-line to-do
moo = 4.

* TODO Here is a block to-do
*  with multiple lines that
*  end here
DATA lt_foo TYPE TABLE OF string.
LOOP AT lt_foo INTO DATA(lv_foo).
  " TODO Here is a multi-line to-do
  "  with 3 lines that
  "  end here
  WRITE lv_foo.
ENDLOOP.
```

In ABAP, you can use `*` at the beginning of a line or `"` at other positions for comments. There is no end-of-comment marker, so I'm thinking it should be as follows:

```json
  {
    "language": "ABAP",
    "markers": [
      {
        "type": "line",
        "pattern": "\""
      },
      {
        "type": "line",
        "pattern": "\*"
      }
    ]
  },
```

If you are ok with it, I will open an PR.

### PR DESCRIPTION
**Pull request by mbtools**
Reference to the documentation of comment syntax:

ABAP
https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abencomment.htm

ABAP CDS
https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abencds_general_syntax_rules.htm

Closes #85

### CODE REVIEW

**Comment by alstr** [comment]
Looks good, I think we might need to escape the `*` line comment though?

**Comment by mbtools** [comment]
When I edited the JSON using Github web editor, it actually complained about escaping `*`, so I took it out. But I'm not familiar with Python reading the JSON or using it in a regex, which might require it. I can put it back, of course.

**Comment by mbtools** [comment]
+updated readme

**Comment by alstr** [comment]
> When I edited the JSON using Github web editor, it actually complained about escaping `*`, so I took it out. But I'm not familiar with Python reading the JSON or using it in a regex, which might require it. I can put it back, of course.

No problem. I just tweaked the escape as it should be `\\*` to get it to work with the current setup. :smile: I think eventually I would like to bring the escaping into the action rather than the syntax file but for now to avoid breaking things this is the easiest solution.

**Comment by alstr** [comment]
Let me know if it works for you, should do.

**Pull request merged**
