### PR TITLE
Adds support for solidity

### PR DESCRIPTION
**Pull request by naps62**

### CODE REVIEW

**Comment by naps62** [comment]
Just noticed there's a blocker with this one: linguist/languages.yml defined solidity with `ace_mode: text`, which is what's used by this action to determine the language being used

this means tests currently fail because they fail to find issues with the given language name.

I don't see any existing setup for adding exceptions for this, but I imagine, since in this context overriding the ace_mode should still work, it should be doable somewhere?

On a separate note, I did notice that Swift also comes with `ace_mode: text`, but there are no tests for that language. presumably they would fail too

**Comment by alstr** [comment]
I think if the `ace_mode` is `text`, we should just update the existing test for that, incrementing the total by however many.

It's a bit confusing but that is what has been done in similar cases so far.

So I'd remove the hotfix and the tests added, and just update the existing tests for `ace_mode` equals `text`. Hopefully that should work.

**Comment by naps62** [comment]
ah, didn't know that was the case, I assumed the functionality would break too. just updated the PR

**Comment by alstr** [comment]
Great, thanks.

**Pull request merged**
