### PR TITLE
Update syntax.json to add Vlang

### PR DESCRIPTION
**Pull request by ulises-jeremias**
Adds support for [V](https://vlang.io/)

### CODE REVIEW

**Comment by alstr** [comment]
Thanks for the submission. Please could you take a look at adding a test for the new language? It should be relatively straightforward; just copy/paste and tweak an existing test, then add add a code snippet to each diff file.

**Comment by ulises-jeremias** [comment]
@alstr sure! I'll do it asap

**Comment by ulises-jeremias** [comment]
hey! sorry for the delay. I just pulled master into my branch and I was about to add a test for V but I'm not sure how to do it with the diff files :/ can I ask you for some guidance on this?

**Comment by alstr** [comment]
Sure, no problem.

1. Add a snippet to the two test diff files with one or more TODOs in. You could copy and paste this from another repo or see the other languages and adjust them.
2. Add a test to `NewIssueTests` and `ClosedIssueTests` along the lines of:

```
    def test_vlang_issues(self):
        self.assertEqual(count_issues_for_file_type(self.raw_issues, 'golang'), 2)
```

The language there is `golang` as it is based on the `ace_mode` for the language here: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

The number is of course the number of TODOs you expect to be created/closed.

**Comment by alstr** [comment]
Closing due to inactivity but feel free to reopen.

**Pull request closed without merging**
