### PR TITLE
Add syntax for Dart

### PR DESCRIPTION
**Pull request by fdietze**
What else needs to be done?

### CODE REVIEW

**Comment by alstr** [comment]
Nothing, all looks good. Thanks.

**Comment by alstr** [comment]
For this to take effect, just update your workflow file to target `todo-to-issue-action@master` (if currently `v3.0.1-beta`) until the next release.

**Comment by fdietze** [comment]
hmm, I guess I did something wrong. It crashed...

```
Traceback (most recent call last):
  File "/app/main.py", line 456, in <module>
    raw_issues = TodoParser().parse(last_diff)
  File "/app/main.py", line 193, in __init__
    self.syntax_dict = syntax_request.json()
  File "/app/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 257 column 1 (char 3851)
```

**Comment by alstr** [comment]
Looks like you added an invalid comma at the end of the array, which I missed. I’ve removed that so it should work now.

**Pull request merged**
